### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by timeinpixels** [zusamarehan/laravel-notion-renderer#8]
I am trying to install it with composer and I am getting:

` [InvalidArgumentException]
  Could not find a matching version of package rehan/laravel-notion-renderer. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).`

What could be the problem?

**Comment by zusamarehan** [comment]
Try again, there is no problem with installing the package. 

```composer require rehankanak/laravel-notion-renderer ```
